DROP TABLE idempotency_records;

CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    response_status INTEGER NOT NULL,
    response_body TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_idempotency_key_user_endpoint
        UNIQUE (idempotency_key, user_id, endpoint),

    CONSTRAINT fk_idempotency_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE INDEX idx_idempotency_records_user_id
    ON idempotency_records(user_id);

